"""Helper: write map_reduce_engine.py with correct content"""
import os

content = (
    "import json\n"
    "import re\n"
    "from typing import List, Dict, Any\n"
    "import requests\n"
    "from config.settings import GROQ_API_KEY\n"
    "from utils.logger import setup_logger\n"
    "\n"
    "logger = setup_logger('MapReduceEngine')\n"
    "GROQ_URL = 'https://api.groq.com/openai/v1/chat/completions'\n"
    "\n"
    "MAP_SCHEMA = (\n"
    "    '{\"partial_script\":[{\"speaker\":\"x\",\"timestamp\":\"MM:SS\",\"text\":\"x\"}],'\n"
    "    ' \"partial_keywords\":[\"k\"]}'\n"
    ")\n"
    "REDUCE_SCHEMA = (\n"
    "    '{\"speaker_type\":\"Solo\",\"speakers\":[\"N\"],'\n"
    "    ' \"ai_topics\":[\"T\"],\"summary\":\"x\"}'\n"
    ")\n"
    "\n"
    "\n"
    "class MapReduceTextEngine:\n"
    "    def __init__(self):\n"
    "        self.api_key = GROQ_API_KEY\n"
    "\n"
    "    def _call_groq(self, model: str, system_prompt: str, user_content: str) -> str:\n"
    "        if not self.api_key:\n"
    "            logger.error('GROQ_API_KEY not configured.')\n"
    "            return ''\n"
    "        headers = {\n"
    "            'Authorization': f'Bearer {self.api_key}',\n"
    "            'Content-Type': 'application/json',\n"
    "        }\n"
    "        payload = {\n"
    "            'model': model,\n"
    "            'messages': [\n"
    "                {'role': 'system', 'content': system_prompt},\n"
    "                {'role': 'user',   'content': user_content},\n"
    "            ],\n"
    "            'temperature': 0.1,\n"
    "            'response_format': {'type': 'json_object'},\n"
    "        }\n"
    "        try:\n"
    "            res = requests.post(GROQ_URL, json=payload, headers=headers, timeout=45)\n"
    "            res.raise_for_status()\n"
    "            return res.json()['choices'][0]['message']['content']\n"
    "        except Exception as e:\n"
    "            logger.error(f'Groq call failed model={model}: {e}')\n"
    "            return ''\n"
    "\n"
    "    @staticmethod\n"
    "    def _chunk_text(text: str, chunk_size: int = 3000, overlap: int = 400) -> List[str]:\n"
    "        segments = re.split(r'\\[SEGMENT BREAK @\\d{2}:\\d{2}\\]', text)\n"
    "        chunks: List[str] = []\n"
    "        buffer = ''\n"
    "        for seg in segments:\n"
    "            seg = seg.strip()\n"
    "            if not seg:\n"
    "                continue\n"
    "            combined = (buffer + '\\n' + seg).strip() if buffer else seg\n"
    "            if len(combined.split()) <= chunk_size:\n"
    "                buffer = combined\n"
    "            else:\n"
    "                if buffer:\n"
    "                    chunks.append(buffer)\n"
    "                words = seg.split()\n"
    "                start = 0\n"
    "                while start < len(words):\n"
    "                    end = min(start + chunk_size, len(words))\n"
    "                    chunks.append(' '.join(words[start:end]))\n"
    "                    start += chunk_size - overlap\n"
    "                buffer = ''\n"
    "        if buffer:\n"
    "            chunks.append(buffer)\n"
    "        return chunks if chunks else [text]\n"
    "\n"
    "    @staticmethod\n"
    "    def _map_prompt() -> str:\n"
    "        return (\n"
    "            'You are an expert AI podcast transcript analyzer.\\n'\n"
    "            'Timestamps are [MM:SS]. [SEGMENT BREAK @MM:SS] = strong speaker-change boundary.\\n\\n'\n"
    "            'Tasks:\\n'\n"
    "            '1. Register ALL names mentioned in context (e.g. Thanks David).\\n'\n"
    "            '2. Label each line with a speaker. Ambiguous -> [Unverified Speaker N]. Never blend speakers.\\n'\n"
    "            '3. Extract 3-5 LLM technical keywords.\\n\\n'\n"
    "            'Output ONLY valid JSON: ' + MAP_SCHEMA\n"
    "        )\n"
    "\n"
    "    @staticmethod\n"
    "    def _reduce_prompt(title: str) -> str:\n"
    "        return (\n"
    "            f'Master Editor. Video: {title}\\n\\n'\n"
    "            '1. Resolve [Unverified Speaker N] across all segments.\\n'\n"
    "            '2. Deduplicate into 2-5 LLM topics.\\n'\n"
    "            '3. Classify: Solo / Interview / Group.\\n'\n"
    "            '4. Write 2-3 sentence summary.\\n\\n'\n"
    "            'Output ONLY valid JSON: ' + REDUCE_SCHEMA\n"
    "        )\n"
    "\n"
    "    def run_pipeline(self, full_text: str, meta: Dict[str, Any]) -> Dict[str, Any]:\n"
    "        if not full_text.strip():\n"
    "            return self._fallback('empty_text')\n"
    "        chunks = self._chunk_text(full_text)\n"
    "        logger.info(f'MapReduce: {len(chunks)} chunks, title={meta.get(\"title\", \"\")!r}')\n"
    "        map_prompt = self._map_prompt()\n"
    "        map_results: List[str] = []\n"
    "        for i, chunk in enumerate(chunks):\n"
    "            raw = self._call_groq(\n"
    "                'llama3-8b-8192', map_prompt,\n"
    "                f'Segment {i+1}/{len(chunks)}:\\n\\n{chunk}'\n"
    "            )\n"
    "            if raw:\n"
    "                map_results.append(raw)\n"
    "        if not map_results:\n"
    "            return self._fallback('all_map_failed')\n"
    "        reduce_raw = self._call_groq(\n"
    "            'llama3-70b-8192',\n"
    "            self._reduce_prompt(meta.get('title', 'Unknown')),\n"
    "            '\\n===SEG===\\n'.join(map_results),\n"
    "        )\n"
    "        final = self._parse_json_safe(reduce_raw)\n"
    "        if not final:\n"
    "            return self._fallback('reduce_failed')\n"
    "        script: List[Dict] = []\n"
    "        seen: set = set()\n"
    "        for r in map_results:\n"
    "            d = self._parse_json_safe(r)\n"
    "            for entry in d.get('partial_script', []):\n"
    "                key = (entry.get('speaker'), entry.get('timestamp'), entry.get('text', '')[:60])\n"
    "                if key not in seen:\n"
    "                    seen.add(key)\n"
    "                    script.append(entry)\n"
    "        final['dialogue_script'] = script[:120]\n"
    "        return final\n"
    "\n"
    "    @staticmethod\n"
    "    def _parse_json_safe(raw: str) -> Dict[str, Any]:\n"
    "        if not raw:\n"
    "            return {}\n"
    "        try:\n"
    "            clean = re.sub(r'```(?:json)?\\s*|\\s*```', '', raw).strip()\n"
    "            return json.loads(clean)\n"
    "        except (json.JSONDecodeError, ValueError):\n"
    "            return {}\n"
    "\n"
    "    @staticmethod\n"
    "    def _fallback(reason: str = 'unknown') -> Dict[str, Any]:\n"
    "        logger.warning(f'MapReduce fallback: {reason}')\n"
    "        return {\n"
    "            'speaker_type': 'Solo',\n"
    "            'speakers': ['Speaker A'],\n"
    "            'ai_topics': ['LLM'],\n"
    "            'summary': f'Unavailable ({reason}).',\n"
    "            'dialogue_script': [],\n"
    "        }\n"
)

os.makedirs("core", exist_ok=True)
with open("core/map_reduce_engine.py", "w", encoding="utf-8") as f:
    f.write(content)
print("Written successfully")
